### ISSUE TITLE
Why does this library reference u8?

### ISSUE THREAD

**Issue by nickray** [dalek-cryptography/subtle#59]
The asymmetry between `unwrap_u8` and `From<u8> for Choice` bothers my OCD.

Similarly, the statement "[Choice] (...) is a wrapper around a u8, which should have the value either 1 (true) or 0 (false)" together with the `debug_assert`ions on this.

Finally, there is some vagueness about the compiler "seeing through" wrapped `bool`s, which I'd wager is equivalent to its power to see through wrapped `u8`s.

And given that all primitive integral types can be converted to bool via `x != 0`, I'd like to suggest removing `u8` completely from the public API, including the `unwrap_u8` method, and replacing with paired `From<bool> for Choice` and `From<Choice> for bool`.

Thoughts?

**Comment by hdevalence** [comment]
The asymmetry is intentional. Users of the library are intended to either (more commonly) receive `Choice` values or (less commonly) construct `Choice` values, and then use those `Choice`s to do constant-time operations, not to convert them back into `bool`s for use with branches etc.

The method is called `unwrap_u8` to indicate that it "unwraps" the type-safe abstraction to provide a "raw" value.  It is an escape hatch, which may be required in order to write custom implementations of the `subtle` traits (e.g., in the SIMD backend of `curve25519-dalek`), but it is not supposed to be the common-path.

Using `x != 0` does not work, because that compiles into a branch – the decision to use `u8`s rather than `bool`s was intentional.

**Comment by nickray** [comment]
Hmm, so if you see `unwrap_u8` as unsafe, maybe it should be an unsafe method?

**Comment by hdevalence** [comment]
I don't think that `unsafe` is appropriate here, because it indicates that something is outside of the Rust abstract machine, rather than just "this API has sharp edges and can be misused".
