### ISSUE TITLE
Add a `CtOption` to `Option` conversion?

### ISSUE THREAD

**Issue by gendx** [dalek-cryptography/subtle#62]
For now, if one wants to convert a `CtOption` to an `Option` (say, at the end of a computation, when constant-time doesn't matter anymore) they need to manually write an `if ... else` block.

```
let foo: CtOption<T> = ...
let bar: Option<T> = if foo.is_some().into() {
    foo.unwrap()
} else {
    None
};
```

Would it make sense to expose an `unwrap_option` method?

- On the one hand, this would allow more idiomatic Rust constructs, e.g. early return with `?` such as `let bar: T = foo.unwrap_option()?;`.
- On the other hand, one can argue that an `if ... else` block is more explicit, which allows to more easily spot the variable-timeness of it.

**Comment by hdevalence** [comment]
Rather than an `unwrap_option` method, if we did this I think that the best API would simply be `impl From<CtOption<T>> for Option<T>`.  The `unwrap_u8` naming is intended to indicate that it's an escape hatch, whereas this would just be an ordinary conversion (in the same way that there's `impl From<Choice> for bool`).

**Comment by gendx** [comment]
Thinking about more, it seems to me that an implicit non-constant-time conversion to `Option` would be a bad idea. The manual `if ... else` is clearer.
