### ISSUE TITLE
Choice: invariant not upheld in release mode

### ISSUE THREAD

**Issue by bmwill** [dalek-cryptography/subtle#66]
From taking a look at the documentation the `Choice` type is meant to be a wrapper around a `0u8` or a `1u8`. This invariant is upheld while running in debug mode (since debug_asserts are used) but isn't upheld when running in release mode.
This simple example illustrates the behavior:
```rust
fn main() {
    let c: Choice = 3u8.into();
    println!("{:?}", c);
}
```
```
> cargo run
thread 'main' panicked at 'assertion failed: (input == 0u8) | (input == 1u8)'
> cargo run --release
Choice(3)
```

**Comment by hdevalence** [comment]
Yep, this is expected behavior, although it could perhaps be documented better that it's the user's responsibility to uphold the invariant. 

I'm not sure what the alternative would be -- it's not possible to branch on the value of the `u8` inside of the impl because the code is supposed to be constant time, at least in release mode, and all of the optional types in Rust involve branching to determine whether the value is present.

So I think that the conversion has to be infallible.  Perhaps it shouldn't have been a `From` impl, but that's the way it is now, and I think it's not a big problem that it's the user's responsibility to uphold the invariant.

In debug mode, this is a hard failure, so to me this seems like the same category of behaviour as integer overflows, which are bugs in user programs that are revealed only in debug mode but not in release mode.
