### ISSUE TITLE
Nightly building issue

### ISSUE THREAD

**Issue by mikelodder7** [dalek-cryptography/subtle#72]
When I build with the latest nightly now I get the following error

```
error: the legacy LLVM-style asm! syntax is no longer supported
   --> /home/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-2.2.2/src/lib.rs:150:14
    |
150 |     unsafe { asm!("" : "=r"(input) : "0"(input) ) }
    |              ----^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |              |
    |              help: replace with: `llvm_asm!`
    |
    = note: consider migrating to the new asm! syntax specified in RFC 2873
    = note: alternatively, switch to llvm_asm! to keep your code working as it is
```
Not sure why I get this in 2.2.3 either. Is this the right place to put this?

**Comment by hdevalence** [comment]
Hmm, it looks like it's trying to build `2.2.2` instead of `2.2.3`, which is odd. Does `cargo update` help? Otherwise, are you specifying subtle yourself, or through a transitive dependency? If you're specifying it yourself, what version did you specify? If you pick it up from a transitive dependency, what crates are depending on subtle?

**Comment by isislovecruft** [comment]
Closing because the bug reporter disappeared, which I assume means a `cargo update` fixed the issue. If not, feel free to reopen.
